module.exports = {
  apps: [
    {
      name: 'backend',
      cwd: '/var/www/markstrades/backend',
      script: 'venv/bin/gunicorn',
      args: 'config.wsgi:application --bind 127.0.0.1:8000 --workers 3 --timeout 120',
      interpreter: 'none',
      env: {
        DJANGO_SETTINGS_MODULE: 'config.settings',
        PATH: '/var/www/markstrades/backend/venv/bin:' + process.env.PATH,
      },
      watch: false,
      max_memory_restart: '500M',
      error_file: '/var/www/markstrades/logs/backend-error.log',
      out_file: '/var/www/markstrades/logs/backend-out.log',
      merge_logs: true,
      time: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
    },
    {
      name: 'frontend',
      cwd: '/var/www/markstrades/frontend',
      script: 'npm',
      args: 'start',
      interpreter: 'none',
      env: {
        NODE_ENV: 'production',
        PORT: '3000',
      },
      watch: false,
      max_memory_restart: '500M',
      error_file: '/var/www/markstrades/logs/frontend-error.log',
      out_file: '/var/www/markstrades/logs/frontend-out.log',
      merge_logs: true,
      time: true,
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
    },
  ],
};
