# Generated by Django 5.0.1 on 2025-12-07 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='licenseverificationlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'License Verification Log', 'verbose_name_plural': 'License Verification Logs'},
        ),
        migrations.CreateModel(
            name='EASettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_range_start', models.DecimalField(decimal_places=2, default=4400, help_text='BUY Range Start Price', max_digits=10)),
                ('buy_range_end', models.DecimalField(decimal_places=2, default=4000, help_text='BUY Range End Price', max_digits=10)),
                ('buy_gap_pips', models.DecimalField(decimal_places=2, default=3.0, help_text='BUY Gap between orders (Pips)', max_digits=10)),
                ('max_buy_orders', models.IntegerField(default=4, help_text='Maximum BUY orders at a time')),
                ('buy_take_profit_pips', models.DecimalField(decimal_places=2, default=50.0, help_text='BUY Take Profit (Pips, 0=disabled)', max_digits=10)),
                ('buy_stop_loss_pips', models.DecimalField(decimal_places=2, default=0.0, help_text='BUY Stop Loss (Pips, 0=disabled)', max_digits=10)),
                ('buy_trailing_start_pips', models.DecimalField(decimal_places=2, default=3.0, help_text='BUY Start trailing after X pips profit', max_digits=10)),
                ('buy_initial_sl_pips', models.DecimalField(decimal_places=2, default=2.0, help_text='BUY Initial SL distance when trailing starts', max_digits=10)),
                ('buy_trailing_ratio', models.DecimalField(decimal_places=2, default=0.5, help_text='BUY SL movement ratio', max_digits=10)),
                ('buy_max_sl_distance', models.DecimalField(decimal_places=2, default=15.0, help_text='BUY Maximum SL distance from price (pips)', max_digits=10)),
                ('buy_trailing_step_pips', models.DecimalField(decimal_places=2, default=0.5, help_text='BUY Minimum step to update SL (pips)', max_digits=10)),
                ('sell_range_start', models.DecimalField(decimal_places=2, default=4400, help_text='SELL Range Start Price', max_digits=10)),
                ('sell_range_end', models.DecimalField(decimal_places=2, default=4000, help_text='SELL Range End Price', max_digits=10)),
                ('sell_gap_pips', models.DecimalField(decimal_places=2, default=3.0, help_text='SELL Gap between orders (Pips)', max_digits=10)),
                ('max_sell_orders', models.IntegerField(default=4, help_text='Maximum SELL orders at a time')),
                ('sell_take_profit_pips', models.DecimalField(decimal_places=2, default=50.0, help_text='SELL Take Profit (Pips, 0=disabled)', max_digits=10)),
                ('sell_stop_loss_pips', models.DecimalField(decimal_places=2, default=0.0, help_text='SELL Stop Loss (Pips, 0=disabled)', max_digits=10)),
                ('sell_trailing_start_pips', models.DecimalField(decimal_places=2, default=3.0, help_text='SELL Start trailing after X pips profit', max_digits=10)),
                ('sell_initial_sl_pips', models.DecimalField(decimal_places=2, default=2.0, help_text='SELL Initial SL distance when trailing starts', max_digits=10)),
                ('sell_trailing_ratio', models.DecimalField(decimal_places=2, default=0.5, help_text='SELL SL movement ratio', max_digits=10)),
                ('sell_max_sl_distance', models.DecimalField(decimal_places=2, default=15.0, help_text='SELL Maximum SL distance from price (pips)', max_digits=10)),
                ('sell_trailing_step_pips', models.DecimalField(decimal_places=2, default=0.5, help_text='SELL Minimum step to update SL (pips)', max_digits=10)),
                ('lot_size', models.DecimalField(decimal_places=2, default=1.0, help_text='Lot Size per order', max_digits=10)),
                ('enable_breakeven_tp', models.BooleanField(default=True, help_text='Enable Breakeven TP for all trades')),
                ('breakeven_buy_tp_pips', models.DecimalField(decimal_places=2, default=2.0, help_text='Breakeven TP for BUY (pips above avg price)', max_digits=10)),
                ('breakeven_sell_tp_pips', models.DecimalField(decimal_places=2, default=2.0, help_text='Breakeven TP for SELL (pips below avg price)', max_digits=10)),
                ('manage_all_trades', models.BooleanField(default=True, help_text='Manage ALL trades (ignore magic number)')),
                ('enable_buy_be_recovery', models.BooleanField(default=True, help_text='Enable BUY Recovery Orders')),
                ('buy_be_recovery_lot_min', models.DecimalField(decimal_places=2, default=1.0, help_text='BUY: Minimum lot for recovery', max_digits=10)),
                ('buy_be_recovery_lot_max', models.DecimalField(decimal_places=2, default=5.0, help_text='BUY: Maximum lot for recovery', max_digits=10)),
                ('buy_be_recovery_lot_increase', models.DecimalField(decimal_places=2, default=10.0, help_text='BUY: Lot increase % per order', max_digits=10)),
                ('max_buy_be_recovery_orders', models.IntegerField(default=30, help_text='BUY: Max recovery orders')),
                ('enable_sell_be_recovery', models.BooleanField(default=True, help_text='Enable SELL Recovery Orders')),
                ('sell_be_recovery_lot_min', models.DecimalField(decimal_places=2, default=0.25, help_text='SELL: Minimum lot for recovery', max_digits=10)),
                ('sell_be_recovery_lot_max', models.DecimalField(decimal_places=2, default=5.0, help_text='SELL: Maximum lot for recovery', max_digits=10)),
                ('sell_be_recovery_lot_increase', models.DecimalField(decimal_places=2, default=10.0, help_text='SELL: Lot increase % per order', max_digits=10)),
                ('max_sell_be_recovery_orders', models.IntegerField(default=30, help_text='SELL: Max recovery orders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ea_settings', to='core.license')),
            ],
            options={
                'verbose_name': 'EA Settings',
                'verbose_name_plural': 'EA Settings',
            },
        ),
    ]
