# Generated by Django 5.0.1 on 2025-12-07 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_licenseverificationlog_options_easettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('account_equity', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('account_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('account_margin', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('account_free_margin', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_buy_positions', models.IntegerField(default=0)),
                ('total_sell_positions', models.IntegerField(default=0)),
                ('total_buy_lots', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_sell_lots', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_buy_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_sell_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('symbol', models.CharField(default='', max_length=20)),
                ('current_price', models.DecimalField(decimal_places=5, default=0, max_digits=15)),
                ('open_positions', models.JSONField(blank=True, default=list)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_data', to='core.license')),
            ],
            options={
                'verbose_name': 'Trade Data',
                'verbose_name_plural': 'Trade Data',
                'ordering': ['-last_update'],
            },
        ),
    ]
