# Generated by Django 5.0.1 on 2025-12-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tradedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='easettings',
            name='investment_amount',
            field=models.DecimalField(decimal_places=2, default=1000, help_text='Investment amount in USD', max_digits=15),
        ),
    ]
