# Generated by Django 5.0.1 on 2025-12-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_easettings_investment_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultEASettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Settings', help_text='Name for this settings template', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Use this as the active default template')),
                ('base_investment', models.DecimalField(decimal_places=2, default=100, help_text='Base investment amount for lot calculation', max_digits=10)),
                ('base_lot_size', models.DecimalField(decimal_places=4, default=0.05, help_text='Lot size per $100 investment', max_digits=10)),
                ('base_recovery_lot_min', models.DecimalField(decimal_places=4, default=0.05, help_text='Recovery lot min per $100 investment', max_digits=10)),
                ('buy_range_start', models.DecimalField(decimal_places=2, default=100000, help_text='BUY Range Start Price', max_digits=10)),
                ('buy_range_end', models.DecimalField(decimal_places=2, default=80000, help_text='BUY Range End Price', max_digits=10)),
                ('buy_gap_pips', models.DecimalField(decimal_places=2, default=3.0, help_text='BUY Gap between orders (Pips)', max_digits=10)),
                ('max_buy_orders', models.IntegerField(default=5, help_text='Maximum BUY orders at a time')),
                ('buy_take_profit_pips', models.DecimalField(decimal_places=2, default=50.0, help_text='BUY Take Profit (Pips)', max_digits=10)),
                ('buy_stop_loss_pips', models.DecimalField(decimal_places=2, default=0.0, help_text='BUY Stop Loss (Pips)', max_digits=10)),
                ('buy_trailing_start_pips', models.DecimalField(decimal_places=2, default=3.0, help_text='BUY Trailing Start (Pips)', max_digits=10)),
                ('buy_initial_sl_pips', models.DecimalField(decimal_places=2, default=2.0, help_text='BUY Initial SL (Pips)', max_digits=10)),
                ('buy_trailing_ratio', models.DecimalField(decimal_places=2, default=0.5, help_text='BUY Trailing Ratio', max_digits=10)),
                ('buy_max_sl_distance', models.DecimalField(decimal_places=2, default=15.0, help_text='BUY Max SL Distance (Pips)', max_digits=10)),
                ('buy_trailing_step_pips', models.DecimalField(decimal_places=2, default=0.5, help_text='BUY Trailing Step (Pips)', max_digits=10)),
                ('sell_range_start', models.DecimalField(decimal_places=2, default=80000, help_text='SELL Range Start Price', max_digits=10)),
                ('sell_range_end', models.DecimalField(decimal_places=2, default=100000, help_text='SELL Range End Price', max_digits=10)),
                ('sell_gap_pips', models.DecimalField(decimal_places=2, default=3.0, help_text='SELL Gap between orders (Pips)', max_digits=10)),
                ('max_sell_orders', models.IntegerField(default=5, help_text='Maximum SELL orders at a time')),
                ('sell_take_profit_pips', models.DecimalField(decimal_places=2, default=50.0, help_text='SELL Take Profit (Pips)', max_digits=10)),
                ('sell_stop_loss_pips', models.DecimalField(decimal_places=2, default=0.0, help_text='SELL Stop Loss (Pips)', max_digits=10)),
                ('sell_trailing_start_pips', models.DecimalField(decimal_places=2, default=3.0, help_text='SELL Trailing Start (Pips)', max_digits=10)),
                ('sell_initial_sl_pips', models.DecimalField(decimal_places=2, default=2.0, help_text='SELL Initial SL (Pips)', max_digits=10)),
                ('sell_trailing_ratio', models.DecimalField(decimal_places=2, default=0.5, help_text='SELL Trailing Ratio', max_digits=10)),
                ('sell_max_sl_distance', models.DecimalField(decimal_places=2, default=15.0, help_text='SELL Max SL Distance (Pips)', max_digits=10)),
                ('sell_trailing_step_pips', models.DecimalField(decimal_places=2, default=0.5, help_text='SELL Trailing Step (Pips)', max_digits=10)),
                ('enable_breakeven_tp', models.BooleanField(default=True, help_text='Enable Breakeven TP')),
                ('breakeven_buy_tp_pips', models.DecimalField(decimal_places=2, default=2.0, help_text='Breakeven BUY TP (Pips)', max_digits=10)),
                ('breakeven_sell_tp_pips', models.DecimalField(decimal_places=2, default=2.0, help_text='Breakeven SELL TP (Pips)', max_digits=10)),
                ('manage_all_trades', models.BooleanField(default=True, help_text='Manage ALL trades')),
                ('enable_buy_be_recovery', models.BooleanField(default=True, help_text='Enable BUY Recovery')),
                ('buy_be_recovery_lot_max', models.DecimalField(decimal_places=2, default=5.0, help_text='BUY Recovery Lot Max', max_digits=10)),
                ('buy_be_recovery_lot_increase', models.DecimalField(decimal_places=2, default=10.0, help_text='BUY Recovery Lot Increase %', max_digits=10)),
                ('max_buy_be_recovery_orders', models.IntegerField(default=30, help_text='Max BUY Recovery Orders')),
                ('enable_sell_be_recovery', models.BooleanField(default=True, help_text='Enable SELL Recovery')),
                ('sell_be_recovery_lot_max', models.DecimalField(decimal_places=2, default=5.0, help_text='SELL Recovery Lot Max', max_digits=10)),
                ('sell_be_recovery_lot_increase', models.DecimalField(decimal_places=2, default=10.0, help_text='SELL Recovery Lot Increase %', max_digits=10)),
                ('max_sell_be_recovery_orders', models.IntegerField(default=30, help_text='Max SELL Recovery Orders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Default EA Settings',
                'verbose_name_plural': 'Default EA Settings',
            },
        ),
        migrations.AlterField(
            model_name='easettings',
            name='buy_be_recovery_lot_min',
            field=models.DecimalField(decimal_places=2, default=0.05, help_text='BUY: Minimum lot for recovery (auto-calculated)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='easettings',
            name='buy_range_end',
            field=models.DecimalField(decimal_places=2, default=80000, help_text='BUY Range End Price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='easettings',
            name='buy_range_start',
            field=models.DecimalField(decimal_places=2, default=100000, help_text='BUY Range Start Price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='easettings',
            name='investment_amount',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Investment amount in USD', max_digits=15),
        ),
        migrations.AlterField(
            model_name='easettings',
            name='lot_size',
            field=models.DecimalField(decimal_places=2, default=0.05, help_text='Lot Size per order (auto-calculated)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='easettings',
            name='max_buy_orders',
            field=models.IntegerField(default=5, help_text='Maximum BUY orders at a time'),
        ),
        migrations.AlterField(
            model_name='easettings',
            name='max_sell_orders',
            field=models.IntegerField(default=5, help_text='Maximum SELL orders at a time'),
        ),
        migrations.AlterField(
            model_name='easettings',
            name='sell_be_recovery_lot_min',
            field=models.DecimalField(decimal_places=2, default=0.05, help_text='SELL: Minimum lot for recovery (auto-calculated)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='easettings',
            name='sell_range_end',
            field=models.DecimalField(decimal_places=2, default=100000, help_text='SELL Range End Price', max_digits=10),
        ),
        migrations.AlterField(
            model_name='easettings',
            name='sell_range_start',
            field=models.DecimalField(decimal_places=2, default=80000, help_text='SELL Range Start Price', max_digits=10),
        ),
    ]
