# Generated by Django 5.0.1 on 2025-12-07 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_defaulteasettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EAActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('CONNECT', 'EA Connected'), ('DISCONNECT', 'EA Disconnected'), ('MODE', 'Trading Mode'), ('OPEN_BUY', 'Open Buy Position'), ('OPEN_SELL', 'Open Sell Position'), ('CLOSE_BUY', 'Close Buy Position'), ('CLOSE_SELL', 'Close Sell Position'), ('MODIFY', 'Modify Position'), ('TRAILING', 'Trailing Stop'), ('BREAKEVEN', 'Breakeven'), ('RECOVERY', 'Recovery Order'), ('GRID', 'Grid Order'), ('SIGNAL', 'Signal'), ('ERROR', 'Error'), ('WARNING', 'Warning'), ('INFO', 'Info')], default='INFO', max_length=20)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='core.license')),
            ],
            options={
                'verbose_name': 'EA Action Log',
                'verbose_name_plural': 'EA Action Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
