# Generated by Django 5.0.1 on 2025-12-07 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_eaactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='defaulteasettings',
            name='symbol',
            field=models.CharField(choices=[('XAUUSD', 'XAUUSD (Gold)'), ('BTCUSD', 'BTCUSD (Bitcoin)')], default='XAUUSD', help_text='Trading symbol for these settings', max_length=20),
        ),
        migrations.AddField(
            model_name='easettings',
            name='symbol',
            field=models.CharField(choices=[('XAUUSD', 'XAUUSD (Gold)'), ('BTCUSD', 'BTCUSD (Bitcoin)')], default='XAUUSD', help_text='Trading symbol', max_length=20),
        ),
        migrations.AlterField(
            model_name='defaulteasettings',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Use this as the active default template for this symbol'),
        ),
        migrations.AlterField(
            model_name='easettings',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ea_settings', to='core.license'),
        ),
        migrations.AlterUniqueTogether(
            name='defaulteasettings',
            unique_together={('symbol', 'is_active')},
        ),
        migrations.AlterUniqueTogether(
            name='easettings',
            unique_together={('license', 'symbol')},
        ),
    ]
