# Generated by Django 5.0.1 on 2025-12-07 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_defaulteasettings_symbol_easettings_symbol_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultEASettings',
        ),
    ]
