# Generated by Django 5.0.1 on 2025-12-07 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_defaulteasettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='easettings',
            name='breakeven_buy_tp_pips',
        ),
        migrations.RemoveField(
            model_name='easettings',
            name='breakeven_sell_tp_pips',
        ),
        migrations.RemoveField(
            model_name='easettings',
            name='enable_breakeven_tp',
        ),
        migrations.AddField(
            model_name='easettings',
            name='breakeven_buy_trailing_pips',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Breakeven trigger for BUY (pips above avg price)', max_digits=10),
        ),
        migrations.AddField(
            model_name='easettings',
            name='breakeven_initial_sl_pips',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Initial SL distance when trailing starts', max_digits=10),
        ),
        migrations.AddField(
            model_name='easettings',
            name='breakeven_max_sl_distance',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Maximum SL distance from current price', max_digits=10),
        ),
        migrations.AddField(
            model_name='easettings',
            name='breakeven_sell_trailing_pips',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Breakeven trigger for SELL (pips below avg price)', max_digits=10),
        ),
        migrations.AddField(
            model_name='easettings',
            name='breakeven_trailing_ratio',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='SL movement ratio (0.5 = move SL 50% of price movement)', max_digits=10),
        ),
        migrations.AddField(
            model_name='easettings',
            name='breakeven_trailing_start_pips',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Start trailing after X pips profit', max_digits=10),
        ),
        migrations.AddField(
            model_name='easettings',
            name='breakeven_trailing_step_pips',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Minimum step to update SL', max_digits=10),
        ),
        migrations.AddField(
            model_name='easettings',
            name='enable_breakeven_trailing',
            field=models.BooleanField(default=True, help_text='Enable Breakeven Trailing for all trades'),
        ),
    ]
