# Generated by Django 5.0.1 on 2025-12-07 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_easettings_breakeven_buy_tp_pips_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='easettings',
            name='investment_amount',
        ),
        migrations.RemoveField(
            model_name='easettings',
            name='lot_size',
        ),
    ]
