# Generated by Django 5.0.1 on 2025-12-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_easettings_investment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradedata',
            name='pending_orders',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tradedata',
            name='total_pending_orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tradedata',
            name='trading_mode',
            field=models.CharField(default='Normal', max_length=50),
        ),
    ]
