# Generated by Django 5.0.1 on 2025-12-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_tradedata_pending_orders_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EAProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='EA Name (e.g., Gold Scalper Pro)', max_length=100)),
                ('subtitle', models.CharField(help_text='Short subtitle (e.g., Most Popular)', max_length=100)),
                ('description', models.TextField(help_text='Description of the EA')),
                ('min_investment', models.DecimalField(decimal_places=2, help_text='Minimum investment amount', max_digits=10)),
                ('max_investment', models.DecimalField(decimal_places=2, help_text='Maximum investment amount', max_digits=10)),
                ('expected_profit', models.CharField(help_text='Expected profit range (e.g., 100-180%)', max_length=50)),
                ('risk_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('Medium-High', 'Medium-High'), ('High', 'High')], default='Medium', max_length=20)),
                ('trading_style', models.CharField(help_text='Trading style (e.g., Aggressive Scalping)', max_length=100)),
                ('features', models.TextField(help_text='Features separated by comma (e.g., Auto Risk Management, Trailing Stop)')),
                ('color', models.CharField(choices=[('cyan', 'Cyan'), ('yellow', 'Yellow'), ('purple', 'Purple'), ('orange', 'Orange'), ('green', 'Green')], default='cyan', max_length=20)),
                ('is_popular', models.BooleanField(default=False, help_text='Mark as popular/featured')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which to display (lower = first)')),
                ('ea_file', models.FileField(blank=True, help_text='Upload .ex5 file', null=True, upload_to='ea_files/')),
                ('file_name', models.CharField(blank=True, help_text='Custom file name for download', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'EA Product',
                'verbose_name_plural': 'EA Products',
                'ordering': ['display_order', 'min_investment'],
            },
        ),
    ]
