# Generated by Django 5.0.1 on 2025-12-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_eaproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradedata',
            name='closed_positions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
