# Generated by Django 5.0.1 on 2025-12-10 17:29

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_referral_referralpayout_referraltransaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='referral',
            options={'verbose_name': 'Referral', 'verbose_name_plural': 'Referrals'},
        ),
        migrations.AlterModelOptions(
            name='referraltransaction',
            options={'verbose_name': 'Referral Transaction', 'verbose_name_plural': 'Referral Transactions'},
        ),
        migrations.RenameField(
            model_name='referralpayout',
            old_name='notes',
            new_name='admin_notes',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='referred_user',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='status',
        ),
        migrations.RemoveField(
            model_name='referralpayout',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='referraltransaction',
            name='commission_percent',
        ),
        migrations.RemoveField(
            model_name='referraltransaction',
            name='license',
        ),
        migrations.RemoveField(
            model_name='referraltransaction',
            name='paid_at',
        ),
        migrations.AddField(
            model_name='referral',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='referral',
            name='clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='referral',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='referral',
            name='purchases',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referrer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_account', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referral',
            name='signups',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='referralpayout',
            name='payment_details',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='referralpayout',
            name='payment_method',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='referraltransaction',
            name='referred_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referraltransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
