# Generated by Django 5.0.1 on 2025-12-16 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_referral_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(choices=[('CLOSE_POSITION', 'Close Position'), ('CLOSE_ALL_BUY', 'Close All Buy'), ('CLOSE_ALL_SELL', 'Close All Sell'), ('CLOSE_ALL', 'Close All Positions'), ('CLOSE_BULK', 'Close Bulk Positions')], max_length=20)),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('executed', 'Executed'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('result_message', models.TextField(blank=True)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_commands', to='core.license')),
            ],
            options={
                'verbose_name': 'Trade Command',
                'verbose_name_plural': 'Trade Commands',
                'ordering': ['-created_at'],
            },
        ),
    ]
