# Generated by Django 5.0.1 on 2025-12-20 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_tradecommand'),
    ]

    operations = [
        migrations.AddField(
            model_name='eaproduct',
            name='external_download_url',
            field=models.URLField(blank=True, help_text='External download link (if set, store will redirect here)'),
        ),
    ]
