# Generated by Django 5.0.1 on 2025-12-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_eaproduct_external_download_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default="MARK'S AI 3.0", max_length=100)),
                ('site_tagline', models.CharField(blank=True, default='Advanced Gold Scalping EA', max_length=200)),
                ('favicon', models.ImageField(blank=True, help_text='Favicon (recommended: 32x32 or 64x64 PNG/ICO)', null=True, upload_to='site/')),
                ('logo', models.ImageField(blank=True, help_text='Site logo image', null=True, upload_to='site/')),
                ('logo_text', models.CharField(blank=True, default="MARK'S AI", help_text='Text logo if no image', max_length=50)),
                ('logo_version', models.CharField(blank=True, default='3.0', help_text='Version text next to logo', max_length=20)),
                ('support_email', models.EmailField(default='support@markstrades.com', max_length=254)),
                ('telegram_en', models.CharField(default='@MarksAISupport', help_text='English Telegram handle', max_length=100)),
                ('telegram_en_url', models.URLField(blank=True, default='https://t.me/MarksAISupport')),
                ('telegram_cn', models.CharField(default='@MarksAIChinese', help_text='Chinese Telegram handle', max_length=100)),
                ('telegram_cn_url', models.URLField(blank=True, default='https://t.me/MarksAISupportChinese')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
