# Generated by Django 5.0.1 on 2025-12-20 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_sitesettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.SlugField(max_length=50, unique=True)),
                ('wallet_address', models.CharField(max_length=255)),
                ('token_symbol', models.CharField(default='USDT', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Network',
                'verbose_name_plural': 'Payment Networks',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LicensePurchaseRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt5_account', models.CharField(blank=True, max_length=50, null=True)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('txid', models.CharField(blank=True, max_length=255)),
                ('proof', models.FileField(blank=True, null=True, upload_to='payment_proofs/')),
                ('user_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_license', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_request', to='core.license')),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.paymentnetwork')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.subscriptionplan')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_purchase_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'License Purchase Request',
                'verbose_name_plural': 'License Purchase Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
