# Generated by Django 5.0.1 on 2025-12-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_paymentnetwork_licensepurchaserequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMTPSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this SMTP configuration')),
                ('host', models.CharField(default='mail.privateemail.com', help_text='SMTP server hostname (e.g., mail.privateemail.com for Namecheap)', max_length=255)),
                ('port', models.IntegerField(default=587, help_text='SMTP port (587 for TLS, 465 for SSL)')),
                ('use_tls', models.BooleanField(default=True, help_text='Use TLS encryption')),
                ('use_ssl', models.BooleanField(default=False, help_text='Use SSL encryption')),
                ('username', models.EmailField(help_text='SMTP username (usually your email address)', max_length=255)),
                ('password', models.CharField(help_text='SMTP password', max_length=255)),
                ('from_email', models.EmailField(help_text="Default 'From' email address", max_length=255)),
                ('from_name', models.CharField(default='MarksTrades Support', help_text="Default 'From' name", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMTP Settings',
                'verbose_name_plural': 'SMTP Settings',
            },
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_cn',
            field=models.CharField(default='@MarksAISupportChinese', help_text='Chinese Telegram handle', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_en',
            field=models.CharField(default='@MarksAISupportEnglish', help_text='English Telegram handle', max_length=100),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='telegram_en_url',
            field=models.URLField(blank=True, default='https://t.me/MarksAISupportEnglish'),
        ),
    ]
