# Generated by Django 5.0.1 on 2025-12-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_emailpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='admin_notification_email',
            field=models.EmailField(blank=True, default='alimulislam50@gmail.com', max_length=254),
        ),
    ]
