# Generated by Django 5.0.1 on 2025-12-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_sitesettings_admin_notification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensepurchaserequest',
            name='request_number',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True, unique=True),
        ),
    ]
