# Generated by Django 5.0.1 on 2025-12-21 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_licensepurchaserequest_request_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributions', to='core.referral')),
                ('referred_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_attribution', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referral Attribution',
                'verbose_name_plural': 'Referral Attributions',
            },
        ),
        migrations.AddField(
            model_name='referraltransaction',
            name='purchase_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_transaction', to='core.licensepurchaserequest'),
        ),
    ]
