# Generated by Django 5.0 on 2026-02-09 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_referral_attribution_and_purchase_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseMT5Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mt5_account', models.CharField(max_length=50)),
                ('hardware_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='tradedata',
            name='mt5_account',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='tradedata',
            constraint=models.UniqueConstraint(fields=('license', 'mt5_account'), name='unique_tradedata_license_mt5_account'),
        ),
        migrations.AddField(
            model_name='licensemt5account',
            name='license',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mt5_accounts', to='core.license'),
        ),
        migrations.AlterUniqueTogether(
            name='licensemt5account',
            unique_together={('license', 'mt5_account')},
        ),
    ]
