# Generated by Django 5.0 on 2026-02-12 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_licensemt5account_tradedata_mt5_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensepurchaserequest',
            name='extend_license',
            field=models.ForeignKey(blank=True, help_text='License to extend (for extension requests)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extension_requests', to='core.license'),
        ),
        migrations.AddField(
            model_name='licensepurchaserequest',
            name='request_type',
            field=models.CharField(choices=[('new', 'New License'), ('extension', 'License Extension')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='licensepurchaserequest',
            name='issued_license',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_requests', to='core.license'),
        ),
    ]
