# Generated by Django 5.0 on 2026-02-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_licensepurchaserequest_extend_license_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eaproduct',
            name='changelog',
            field=models.TextField(blank=True, help_text='What changed in this version'),
        ),
        migrations.AddField(
            model_name='eaproduct',
            name='last_update_notified_at',
            field=models.DateTimeField(blank=True, help_text='When users were last notified about an update', null=True),
        ),
        migrations.AddField(
            model_name='eaproduct',
            name='version',
            field=models.CharField(default='1.0', help_text='Current version (e.g., 2.0, 3.1)', max_length=20),
        ),
    ]
