# Generated by Django 5.0 on 2026-02-12 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_eaproduct_changelog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name, e.g. PayPal, Bank Transfer, USDT (TRC20)', max_length=100)),
                ('code', models.CharField(help_text='Internal code, e.g. paypal, bank, usdt_trc20', max_length=50, unique=True)),
                ('placeholder', models.CharField(blank=True, help_text="Placeholder text for the details input, e.g. 'Enter your PayPal email'", max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Payout Method',
                'verbose_name_plural': 'Payout Methods',
                'ordering': ['sort_order', 'name'],
            },
        ),
    ]
