# Generated by Django 5.0 on 2026-02-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_add_payout_method_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='nickname',
            field=models.CharField(blank=True, default='', help_text='User-defined nickname for this license', max_length=20),
        ),
    ]
