# Generated by Django 5.0 on 2026-02-12 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_license_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensepurchaserequest',
            name='network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.paymentnetwork'),
        ),
    ]
