# Generated by Django 5.0 on 2026-02-12 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_licensepurchaserequest_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='eaproduct',
            name='is_coming_soon',
            field=models.BooleanField(default=False, help_text="Show as 'Coming Soon' in store (visible but not downloadable)"),
        ),
    ]
