# Generated by Django 5.0 on 2026-02-26 08:49

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_eaproduct_is_coming_soon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EconomicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('currency', models.CharField(help_text='e.g., USD, EUR, GBP', max_length=10)),
                ('impact', models.CharField(choices=[('low', 'Low Impact'), ('medium', 'Medium Impact'), ('high', 'High Impact')], default='medium', max_length=10)),
                ('event_time', models.DateTimeField()),
                ('forecast', models.CharField(blank=True, max_length=50)),
                ('actual', models.CharField(blank=True, max_length=50)),
                ('previous', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Economic Event',
                'verbose_name_plural': 'Economic Events',
                'ordering': ['event_time'],
            },
        ),
        migrations.CreateModel(
            name='FMChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FM Chat Room',
                'verbose_name_plural': 'FM Chat Rooms',
            },
        ),
        migrations.AlterField(
            model_name='tradecommand',
            name='command_type',
            field=models.CharField(choices=[('CLOSE_POSITION', 'Close Position'), ('CLOSE_ALL_BUY', 'Close All Buy'), ('CLOSE_ALL_SELL', 'Close All Sell'), ('CLOSE_ALL', 'Close All Positions'), ('CLOSE_BULK', 'Close Bulk Positions'), ('EA_ON', 'Turn EA ON (FM)'), ('EA_OFF', 'Turn EA OFF (FM)')], max_length=20),
        ),
        migrations.CreateModel(
            name='FMChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('message_type', models.CharField(choices=[('message', 'Regular Message'), ('announcement', 'Announcement'), ('signal', 'Trade Signal'), ('system', 'System Message')], default='message', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fm_chat_messages', to=settings.AUTH_USER_MODEL)),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.fmchatroom')),
            ],
            options={
                'verbose_name': 'FM Chat Message',
                'verbose_name_plural': 'FM Chat Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FMSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('trial', 'Free Trial'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='trial', max_length=20)),
                ('price_at_subscription', models.DecimalField(decimal_places=2, max_digits=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('current_period_start', models.DateTimeField(auto_now_add=True)),
                ('current_period_end', models.DateTimeField()),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fm_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FM Subscription',
                'verbose_name_plural': 'FM Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FMAccountAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ea_active', models.BooleanField(default=True, help_text='Whether EA trading is currently enabled by FM')),
                ('last_toggled_at', models.DateTimeField(blank=True, null=True)),
                ('last_toggled_reason', models.CharField(blank=True, max_length=255)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fm_assignments', to='core.license')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_accounts', to='core.fmsubscription')),
            ],
            options={
                'verbose_name': 'FM Account Assignment',
                'verbose_name_plural': 'FM Account Assignments',
                'unique_together': {('subscription', 'license')},
            },
        ),
        migrations.CreateModel(
            name='FundManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(help_text='Public display name', max_length=100)),
                ('bio', models.TextField(blank=True, help_text='About the fund manager')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='fm_avatars/')),
                ('tier', models.CharField(choices=[('standard', 'Standard'), ('professional', 'Professional'), ('elite', 'Elite')], default='standard', max_length=20)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=Decimal('29.00'), help_text='Monthly subscription price in USD', max_digits=10)),
                ('total_profit_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total profit % across all managed accounts', max_digits=10)),
                ('win_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Win rate percentage', max_digits=5)),
                ('months_active', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=3)),
                ('total_reviews', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('is_verified', models.BooleanField(default=False, help_text='Verified badge')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured on marketplace')),
                ('platform_commission_percent', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Platform takes this % of subscription fee', max_digits=5)),
                ('trading_pairs', models.CharField(default='XAUUSD', help_text='Comma-separated trading pairs', max_length=200)),
                ('trading_style', models.CharField(blank=True, help_text='e.g., Conservative Scalping, Aggressive Grid', max_length=100)),
                ('max_subscribers', models.IntegerField(default=50, help_text='Maximum number of subscribers allowed')),
                ('trial_days', models.IntegerField(default=7, help_text='Free trial period in days (0 = no trial)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fund_manager_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fund Manager',
                'verbose_name_plural': 'Fund Managers',
                'ordering': ['-is_featured', '-average_rating', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='fmsubscription',
            name='fund_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.fundmanager'),
        ),
        migrations.CreateModel(
            name='FMSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Schedule name (e.g., 'No Friday Trading')", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('off_time', models.TimeField(help_text='Time to turn EA OFF (UTC)')),
                ('on_time', models.TimeField(help_text='Time to turn EA back ON (UTC)')),
                ('reason', models.CharField(blank=True, help_text="e.g., 'High impact news window'", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('fund_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.fundmanager')),
            ],
            options={
                'verbose_name': 'FM Schedule',
                'verbose_name_plural': 'FM Schedules',
                'ordering': ['day_of_week', 'off_time'],
            },
        ),
        migrations.CreateModel(
            name='FMPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('gross_amount', models.DecimalField(decimal_places=2, help_text='Total subscription revenue for period', max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, help_text='Platform commission deducted', max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, help_text='Amount payable to FM', max_digits=10)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_details', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('fund_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='core.fundmanager')),
            ],
            options={
                'verbose_name': 'FM Payout',
                'verbose_name_plural': 'FM Payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FMCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_type', models.CharField(choices=[('ea_on', 'Turn EA ON'), ('ea_off', 'Turn EA OFF')], max_length=10)),
                ('target_type', models.CharField(choices=[('all', 'All Subscribers'), ('specific', 'Specific Account')], default='all', max_length=10)),
                ('reason', models.CharField(blank=True, help_text='Why this command was issued (e.g., NFP News)', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('executed', 'Executed'), ('partial', 'Partially Executed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('affected_accounts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('target_assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commands', to='core.fmaccountassignment')),
                ('fund_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='core.fundmanager')),
            ],
            options={
                'verbose_name': 'FM Command',
                'verbose_name_plural': 'FM Commands',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='fmchatroom',
            name='fund_manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='core.fundmanager'),
        ),
        migrations.AlterUniqueTogether(
            name='fmsubscription',
            unique_together={('user', 'fund_manager')},
        ),
        migrations.CreateModel(
            name='FMReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating 1-5')),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fm_reviews', to=settings.AUTH_USER_MODEL)),
                ('fund_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.fundmanager')),
            ],
            options={
                'verbose_name': 'FM Review',
                'verbose_name_plural': 'FM Reviews',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'fund_manager')},
            },
        ),
    ]
