# Generated by Django 5.0 on 2026-02-26 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_badge_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='fmchatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fm_chat_images/'),
        ),
        migrations.AddField(
            model_name='fmchatmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='core.fmchatmessage'),
        ),
        migrations.AddField(
            model_name='fmchatmessage',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='fm_chat_voice/'),
        ),
        migrations.AlterField(
            model_name='fmchatmessage',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='fmchatmessage',
            name='message_type',
            field=models.CharField(choices=[('message', 'Regular Message'), ('announcement', 'Announcement'), ('signal', 'Trade Signal'), ('system', 'System Message'), ('photo', 'Photo'), ('voice', 'Voice Message')], default='message', max_length=20),
        ),
    ]
