# Generated by Django 5.0 on 2026-02-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_chat_media_voice'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradingWaveAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('normal', 'Normal Impact Running'), ('medium', 'Medium Impact Expecting'), ('high', 'High Impact Expecting')], default='normal', max_length=10)),
                ('minutes_before', models.PositiveIntegerField(default=0, help_text='Minutes until impact wave arrives (set 0 for Normal mode)')),
                ('tips', models.TextField(blank=True, default='', help_text="Tips / advice text to show users (e.g., 'Close risky positions before NFP')")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this alert is visible to users')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trading Wave Alert',
                'verbose_name_plural': 'Trading Wave Alert',
            },
        ),
    ]
