# Generated by Django 5.0 on 2026-02-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_tradingwavealert'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradingwavealert',
            options={'ordering': ['mode'], 'verbose_name': 'Trading Wave Alert', 'verbose_name_plural': 'Trading Wave Alerts'},
        ),
        migrations.AddField(
            model_name='tradingwavealert',
            name='activated_at',
            field=models.DateTimeField(blank=True, help_text='Auto-set when you activate the alert. The countdown runs from this moment.', null=True),
        ),
        migrations.AlterField(
            model_name='tradingwavealert',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Turn ON to broadcast this alert to all users'),
        ),
        migrations.AlterField(
            model_name='tradingwavealert',
            name='minutes_before',
            field=models.PositiveIntegerField(default=0, help_text='Minutes until the impact wave arrives. Frontend shows a live countdown from this value.'),
        ),
        migrations.AlterField(
            model_name='tradingwavealert',
            name='mode',
            field=models.CharField(choices=[('normal', 'Normal Impact Running'), ('medium', 'Medium Impact Expecting'), ('high', 'High Impact Expecting')], max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='tradingwavealert',
            name='tips',
            field=models.TextField(blank=True, default='', help_text="Tips / summary text shown to users (e.g., 'Close risky positions before NFP release')"),
        ),
    ]
