# Generated by Django 6.0 on 2026-02-26 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_tradingwavealert_display_name'),
    ]

    operations = [
    ]
