# Generated by Django 5.0 on 2026-03-07 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_emailotp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VPSPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Starter VPS', 'Pro VPS'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('cpu', models.CharField(help_text="e.g. '2 vCPU'", max_length=50)),
                ('ram', models.CharField(help_text="e.g. '4 GB'", max_length=50)),
                ('storage', models.CharField(help_text="e.g. '60 GB SSD'", max_length=50)),
                ('os', models.CharField(default='Windows Server 2022', help_text='Operating system', max_length=100)),
                ('bandwidth', models.CharField(blank=True, default='Unlimited', max_length=50)),
                ('location', models.CharField(blank=True, default='New York, USA', max_length=100)),
                ('price_monthly', models.DecimalField(decimal_places=2, help_text='Monthly price in USD', max_digits=10)),
                ('price_quarterly', models.DecimalField(blank=True, decimal_places=2, help_text='3-month price (optional discount)', max_digits=10, null=True)),
                ('price_yearly', models.DecimalField(blank=True, decimal_places=2, help_text='12-month price (optional discount)', max_digits=10, null=True)),
                ('features', models.JSONField(blank=True, default=list, help_text="List of feature strings, e.g. ['24/7 Uptime', 'Full Admin Access']")),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'VPS Plan',
                'verbose_name_plural': 'VPS Plans',
                'ordering': ['sort_order', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='VPSOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(editable=False, max_length=10, unique=True)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly (3 months)'), ('yearly', 'Yearly (12 months)')], default='monthly', max_length=20)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('txid', models.CharField(blank=True, max_length=255)),
                ('proof', models.FileField(blank=True, null=True, upload_to='vps_payment_proofs/')),
                ('user_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Activation'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.paymentnetwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vps_orders', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='core.vpsplan')),
            ],
            options={
                'verbose_name': 'VPS Order',
                'verbose_name_plural': 'VPS Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VPSServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(help_text='Server IP address', max_length=45)),
                ('rdp_port', models.IntegerField(default=3389, help_text='RDP port')),
                ('username', models.CharField(help_text='RDP login username', max_length=100)),
                ('password', models.CharField(help_text='RDP login password', max_length=255)),
                ('hostname', models.CharField(blank=True, help_text='Server hostname (optional)', max_length=255)),
                ('additional_info', models.TextField(blank=True, help_text='Any extra info for the user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='server', to='core.vpsorder')),
            ],
            options={
                'verbose_name': 'VPS Server',
                'verbose_name_plural': 'VPS Servers',
            },
        ),
    ]
