# Generated by Django 5.0 on 2026-03-08 09:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_vpsplan_vpsorder_vpsserver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VPSDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='VPS discount percentage (e.g., 10.00 for 10% off)', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional expiry date for discount', null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this discount')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vps_discount', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'VPS Discount',
                'verbose_name_plural': 'VPS Discounts',
            },
        ),
    ]
