# Generated by Django 5.0 on 2026-03-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_vpsdiscount'),
    ]

    operations = [
        migrations.AddField(
            model_name='licensepurchaserequest',
            name='want_vps_discount',
            field=models.BooleanField(default=False, help_text='User wants VPS discount eligibility'),
        ),
    ]
