# Generated by Django 5.0 on 2026-03-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_licensepurchaserequest_want_vps_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='default_vps_discount_percent',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Default VPS discount % for paid license purchases (e.g., 10.00 for 10% off). Does NOT apply to free Exness claims.', max_digits=5),
        ),
    ]
