# Generated by Django 6.0 on 2026-03-11 09:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_sitesettings_default_vps_discount_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuidelineCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text='URL-friendly identifier (e.g. getting-started)', unique=True)),
                ('icon', models.CharField(choices=[('Download', 'Download'), ('Shield', 'Shield'), ('Settings', 'Settings'), ('TrendingUp', 'TrendingUp'), ('AlertTriangle', 'AlertTriangle'), ('BookOpen', 'BookOpen'), ('Zap', 'Zap'), ('Target', 'Target'), ('DollarSign', 'DollarSign'), ('Play', 'Play')], default='Play', max_length=30)),
                ('color', models.CharField(choices=[('cyan', 'Cyan'), ('yellow', 'Yellow'), ('purple', 'Purple'), ('green', 'Green'), ('orange', 'Orange'), ('red', 'Red'), ('blue', 'Blue')], default='cyan', max_length=20)),
                ('sort_order', models.IntegerField(default=0, help_text='Lower = shown first')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Guideline Category',
                'verbose_name_plural': 'Guideline Categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='GuidelineVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('youtube_url', models.URLField(help_text='Full YouTube video URL (e.g. https://www.youtube.com/watch?v=abc123)')),
                ('duration', models.CharField(blank=True, help_text='e.g. 5:30', max_length=10)),
                ('sort_order', models.IntegerField(default=0, help_text='Lower = shown first within category')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.guidelinecategory')),
            ],
            options={
                'verbose_name': 'Guideline Video',
                'verbose_name_plural': 'Guideline Videos',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
    ]
