# Generated by Django 5.0 on 2026-03-12 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_guidelinecategory_guidelinevideo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_code', models.CharField(editable=False, help_text='Unique gift voucher code', max_length=32, unique=True)),
                ('status', models.CharField(choices=[('purchased', 'Purchased'), ('delivered', 'Delivered'), ('redeemed', 'Redeemed'), ('expired', 'Expired')], default='purchased', max_length=20)),
                ('buyer_email', models.EmailField(help_text='Email of the person who purchased the gift', max_length=254)),
                ('buyer_name', models.CharField(blank=True, default='', max_length=100)),
                ('recipient_email', models.EmailField(help_text='Email where the gift code will be sent', max_length=254)),
                ('recipient_name', models.CharField(blank=True, default='', max_length=100)),
                ('gift_message', models.TextField(blank=True, default='', help_text='Optional personal message from buyer')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_network', models.CharField(blank=True, default='', max_length=100)),
                ('txid', models.CharField(blank=True, default='', help_text='Transaction ID for payment verification', max_length=255)),
                ('payment_verified', models.BooleanField(default=False)),
                ('redeemed_at', models.DateTimeField(blank=True, null=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_purchases', to=settings.AUTH_USER_MODEL)),
                ('issued_license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gift_source', to='core.license')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.subscriptionplan')),
                ('redeemed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='redeemed_gifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gift License',
                'verbose_name_plural': 'Gift Licenses',
                'ordering': ['-purchased_at'],
            },
        ),
    ]
