# Generated by Django 5.0 on 2026-03-20 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_giftlicense'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradedata',
            name='ea_details',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
