# Generated by Django 5.0 on 2026-03-23 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_tradedata_ea_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='EAControlSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot_size', models.DecimalField(decimal_places=2, default=0.01, help_text='Trade lot size for EA', max_digits=10)),
                ('enable_daily_target', models.BooleanField(default=False, help_text='Enable daily profit target auto-stop')),
                ('daily_balance_target', models.DecimalField(decimal_places=2, default=0, help_text='Daily balance target ($). EA stops when balance reaches this.', max_digits=15)),
                ('daily_equity_target', models.DecimalField(decimal_places=2, default=0, help_text='Daily equity target ($). EA stops when equity reaches this.', max_digits=15)),
                ('cooldown_minutes', models.IntegerField(default=60, help_text='Minutes to keep EA stopped after hitting target before restarting')),
                ('enable_schedule_stop', models.BooleanField(default=False, help_text='Enable scheduled EA stop')),
                ('schedule_stop_hour', models.IntegerField(default=0, help_text='Hour to stop EA (0-23, server time)')),
                ('schedule_stop_minute', models.IntegerField(default=0, help_text='Minute to stop EA (0-59)')),
                ('schedule_stop_duration_minutes', models.IntegerField(default=60, help_text='How long to keep EA stopped (minutes)')),
                ('target_hit_at', models.DateTimeField(blank=True, help_text='When the daily target was last hit', null=True)),
                ('is_target_stopped', models.BooleanField(default=False, help_text='Whether EA is currently stopped due to target hit')),
                ('is_schedule_stopped', models.BooleanField(default=False, help_text='Whether EA is currently stopped due to schedule')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('license', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ea_control', to='core.license')),
            ],
            options={
                'verbose_name': 'EA Control Settings',
                'verbose_name_plural': 'EA Control Settings',
            },
        ),
    ]
