# Generated by GitHub Copilot on 2026-04-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_eacontrolsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eacontrolsettings',
            name='lot_size',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Trade lot size for EA (0 = use EA default)', max_digits=10),
        ),
    ]
